server:
  port: 8080
spring:
  security:
    jwt:
      key: 'juzic'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 5
  web:
    flow:
      period: 3
      limit: 100
      block: 30
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    username: 2833227241@qq.com
    password: ozvlejvotvyddeid
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  servlet:
    multipart:
      enabled: true                   # 启用文件上传功能
      max-file-size: 100MB            # 单个文件最大大小
      max-request-size: 100MB         # 单次请求最大大小
      file-size-threshold: 0          # 文件写入磁盘的阈值
#      location: /tmp                  # 上传文件的临时目录

  datasource:
      url: jdbc:mysql://localhost:3306/yunpan?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

project:
  folder: E:\juzipan
